#!/usr/bin/env bash
# publish-skill.sh — 将本地 skill 打包发布，生成一键安装命令
#
# 用法: publish-skill.sh <skill-name> [skill-dir]
#
# 环境变量:
#   GITHUB_TOKEN   GitHub Personal Access Token（优先）
#   DOCS_API_URL   documents:toPage API 地址（默认 http://165.154.134.82:1002）

set -euo pipefail

SKILL_NAME="${1:-}"
FILE_API_URL="${FILE_API_URL:-http://165.154.134.82:1002}"
DOCS_API_URL="${DOCS_API_URL:-http://165.154.134.82:1002}"

# ── 参数检查 ──────────────────────────────────────────────
if [[ -z "$SKILL_NAME" ]]; then
  echo "用法: $0 <skill-name>" >&2
  echo ""
  echo "本机已安装的 skills:"
  ls ~/.codex/skills/ 2>/dev/null | grep -v '^\.' || echo "  (无)"
  exit 1
fi

# ── 查找 skill 目录 ───────────────────────────────────────
SKILL_DIR="${2:-}"
if [[ -z "$SKILL_DIR" ]]; then
  for candidate in \
    "${HOME}/.codex/skills/${SKILL_NAME}" \
    "${HOME}/.cursor/skills/${SKILL_NAME}" \
    "$(pwd)/skills/${SKILL_NAME}" \
    "$(pwd)/${SKILL_NAME}"; do
    if [[ -d "$candidate" ]]; then
      SKILL_DIR="$candidate"
      break
    fi
  done
fi

if [[ -z "$SKILL_DIR" || ! -d "$SKILL_DIR" ]]; then
  echo "❌ 找不到 skill 目录: ${SKILL_NAME}" >&2
  echo "搜索路径: ~/.codex/skills/ ~/.cursor/skills/ $(pwd)/skills/" >&2
  exit 1
fi

echo "📦 打包 skill: ${SKILL_NAME}"
echo "   来源目录: ${SKILL_DIR}"
echo ""

INSTALL_FILENAME="install-${SKILL_NAME}.sh"

# ── 生成自包含安装脚本 ────────────────────────────────────
INSTALL_SCRIPT=$(mktemp /tmp/install-XXXXXX.sh)
trap 'rm -f "$INSTALL_SCRIPT"' EXIT

{
cat << 'HEADER'
#!/usr/bin/env bash
# Auto-generated one-click install script
# Generated by: publish-skill (https://github.com/ChangfengHU/skill-publisher)
set -euo pipefail

HEADER

echo "SKILL_NAME=\"${SKILL_NAME}\""
echo ""

cat << 'TOOL_SELECT'
# ── 工具选择 ──────────────────────────────────────────────
TARGET="${1:-}"
if [[ -z "$TARGET" ]]; then
  echo "🛠  选择安装到哪个 AI 工具："
  echo "  1) Codex        (~/.codex/skills/)"
  echo "  2) Cursor       (~/.cursor/skills/)"
  echo "  3) Claude       (~/.claude/plugins/)"
  echo "  4) Gemini       (~/.gemini/skills/)"
  echo "  5) Antigravity  (~/.gemini/antigravity/knowledge/)"
  echo "  6) Copilot      (~/.github-copilot/skills/)"
  echo "  7) 全部安装"
  read -rp "请输入编号 [1-7]: " CHOICE
  case "$CHOICE" in
    1) TARGET="codex"       ;;
    2) TARGET="cursor"      ;;
    3) TARGET="claude"      ;;
    4) TARGET="gemini"      ;;
    5) TARGET="antigravity" ;;
    6) TARGET="copilot"     ;;
    7) TARGET="all"         ;;
    *) echo "❌ 无效选项"; exit 1 ;;
  esac
fi

install_to() {
  local dir="$1"
  local name="$SKILL_NAME"
  echo "  📦 → $dir"
  mkdir -p "$dir"
}

case "$TARGET" in
  codex)       DIRS=("$HOME/.codex/skills/$SKILL_NAME")       ;;
  cursor)      DIRS=("$HOME/.cursor/skills/$SKILL_NAME")      ;;
  claude)      DIRS=("$HOME/.claude/plugins/$SKILL_NAME/skills/$SKILL_NAME") ;;
  gemini)      DIRS=("$HOME/.gemini/skills/$SKILL_NAME")      ;;
  antigravity) DIRS=("$HOME/.gemini/antigravity/knowledge/$SKILL_NAME") ;;
  copilot)     DIRS=("$HOME/.github-copilot/skills/$SKILL_NAME") ;;
  all)
    DIRS=(
      "$HOME/.codex/skills/$SKILL_NAME"
      "$HOME/.cursor/skills/$SKILL_NAME"
      "$HOME/.claude/plugins/$SKILL_NAME/skills/$SKILL_NAME"
      "$HOME/.gemini/skills/$SKILL_NAME"
      "$HOME/.gemini/antigravity/knowledge/$SKILL_NAME"
      "$HOME/.github-copilot/skills/$SKILL_NAME"
    ) ;;
  *) echo "❌ 不支持的 target: $TARGET"; exit 1 ;;
esac

echo ""
echo "🚀 安装 skill: $SKILL_NAME"
echo ""
TOOL_SELECT

# ── 嵌入各文件内容 ────────────────────────────────────────
while IFS= read -r -d '' filepath; do
  relpath="${filepath#${SKILL_DIR}/}"
  # 用 base64 编码文件内容，避免 heredoc 特殊字符问题
  encoded=$(base64 < "$filepath")
  echo "# File: ${relpath}"
  echo "write_file() {"
  echo "  local dst=\"\$1/${relpath}\""
  echo "  mkdir -p \"\$(dirname \"\$dst\")\""
  echo "  base64 -d << 'B64EOF' > \"\$dst\""
  echo "${encoded}"
  echo "B64EOF"
  if [[ "$filepath" == *.sh ]]; then
    echo "  chmod +x \"\$dst\""
  fi
  echo "}"
  echo "for d in \"\${DIRS[@]}\"; do write_file \"\$d\"; done"
  echo ""
done < <(find "$SKILL_DIR" -type f -print0 | sort -z)

cat << 'FOOTER'
echo ""
echo "✅ 安装完成！现在你可以对 AI 说："
echo "   (根据 SKILL.md 中描述的触发词与 AI 交互)"
echo ""
FOOTER

} > "$INSTALL_SCRIPT"

chmod +x "$INSTALL_SCRIPT"

# ── 上传脚本到文件服务器 ──────────────────────────────────
echo "📤 上传到文件服务器..."
UPLOAD_RESP=$(curl -s -X POST "${FILE_API_URL}/admin/upload" \
  -F "file=@${INSTALL_SCRIPT};filename=${INSTALL_FILENAME}")

RAW_URL=$(echo "$UPLOAD_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('url',''))" 2>/dev/null || true)

if [[ -n "$RAW_URL" ]]; then
  echo "   ✅ 上传成功: $RAW_URL"
else
  echo "   ⚠️  上传失败: $UPLOAD_RESP"
fi

# ── 上传到 documents:toPage（HTML 文档页）────────────────
DOC_URL=""
SKILL_MD=""
if [[ -f "${SKILL_DIR}/SKILL.md" ]]; then
  SKILL_MD=$(cat "${SKILL_DIR}/SKILL.md")
fi

INSTALL_CMD=""
if [[ -n "$RAW_URL" ]]; then
  INSTALL_CMD="bash <(curl -fsSL ${RAW_URL})"
else
  INSTALL_CMD="(需要 GitHub Token 才能生成安装命令)"
fi

DOC_CONTENT="# ${SKILL_NAME} — 一键安装

## 安装命令

\`\`\`bash
${INSTALL_CMD}
\`\`\`

---

${SKILL_MD}"

DOC_RESP=$(curl -s -X POST "${DOCS_API_URL}/v1beta/documents:toPage" \
  -H "Content-Type: application/json" \
  -d "$(python3 - <<PYEOF
import json, sys
content = """${DOC_CONTENT}"""
print(json.dumps({"content": content, "title": "Install: ${SKILL_NAME}"}))
PYEOF
)" \
  2>/dev/null || true)

DOC_URL=$(echo "$DOC_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin).get('page_url',''))" 2>/dev/null || true)

# ── 本地备份 ──────────────────────────────────────────────
LOCAL_OUT="${HOME}/.codex/skills/.system/published/${INSTALL_FILENAME}"
mkdir -p "$(dirname "$LOCAL_OUT")"
cp "$INSTALL_SCRIPT" "$LOCAL_OUT"

# ── 输出结果 ──────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Skill 发布成功！"
echo ""
echo "📦 Skill: ${SKILL_NAME}"

if [[ -n "$RAW_URL" ]]; then
  echo ""
  echo "🚀 一键安装命令："
  echo ""
  echo "   bash <(curl -fsSL ${RAW_URL})"
  echo ""
fi

if [[ -n "$DOC_URL" ]]; then
  echo "📄 文档页面: ${DOC_URL}"
fi

echo "💾 本地备份: ${LOCAL_OUT}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 机器可读输出（供 agent 解析）
python3 - <<PYEOF
import json
print("PUBLISH_RESULT_JSON=" + json.dumps({
  "skill": "${SKILL_NAME}",
  "install_command": "bash <(curl -fsSL ${RAW_URL})" if "${RAW_URL}" else "",
  "raw_url": "${RAW_URL}",
  "doc_url": "${DOC_URL}",
  "local_backup": "${LOCAL_OUT}"
}))
PYEOF
